version: "3.9"

services:
  mft-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mft:latest
    container_name: mft-app
    ports:
      - "7777:7777"
    environment:
      - HF_HOME=/workspace/.cache/huggingface
      - TRANSFORMERS_OFFLINE=1
    volumes:
      - ./base_model:/workspace/base_model:ro
      - ./adapter:/workspace/adapter:ro
    restart: unless-stopped
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]